<a href="https://colab.research.google.com/github/Fernandarodg/CinD_23-II/blob/main/03_Ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structre?**

Something that let me store several values


# **2. Linear Algebra - Numpy**

Numpy=Numberical Phyton

In [2]:
# Libraries
import numpy as np

## 2.1. **Numpy arrays - Vectors and Matrices**

In [3]:
# column Vector
x = np.array([[1], [2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
# Row Vector
y = np.array([[3, 4, 5]])
print (y)
print(y.shape)

[[3 4 5]]
(1, 3)


In [5]:
# Matriz
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
# A nice trick

## 2.2. Slicing with matrices
 first row, second column
 3 number
 [3] vector
 [2,0] se quita

In [24]:
# Access 1 element

## For vector
### Colum Vector
print(x[1,0])
### Row vector
print(y[0,0])

## For matrix
print(M[0,3])

2
3


IndexError: ignored

In [ ]:
# Exercise - Practice
## Using a for loop display/print the number of the row,
## the number of the column, and the element for
## every element in the Matrix M



In [ ]:
row 1, column 1, element 1
row 2, column 2, element 5

In [27]:
print('row', 1, 'column', 1, 'element', M[0,0])
print('row', 2, 'column', 2, 'element', M[1,1])

row 1 column 1 element 1
row 2 column 2 element 5


In [29]:
for i in range(0,10)
   print(

SyntaxError: ignored