<a href="https://colab.research.google.com/github/Fernandarodg/CinD_23-II/blob/main/03_Ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structre?**

Something that let me store several values


# **2. Linear Algebra - Numpy**

Numpy=Numberical Phyton

In [152]:
# Libraries
import numpy as np

## 2.1. **Numpy arrays - Vectors and Matrices**

In [153]:
# column Vector
x = np.array([[1], [2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [154]:
# Row Vector
y = np.array([[3, 4, 5]])
print (y)
print(y.shape)

[[3 4 5]]
(1, 3)


In [155]:
# Matriz
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [156]:
# A nice trick
n, m= M.shape
print('number of rows in M:' , n)
print('number of columns in M:', m)

number of rows in M: 3
number of columns in M: 3


## 2.2. Slicing with matrices
 first row, second column
 3 number
 [3] vector
 [2,0] se quita

In [189]:
# Access 1 element

## For vector
### Column Vector
print(x[2,0])
### Row vector
print(y[1,1])

## For matrix
print(M[1,1])

TypeError: ignored

In [ ]:
# Exercise - Practice
## Using a for loop display/print the number of the row,
## the number of the column, and the element for
## every element in the Matrix M



In [175]:
row 1, column 1, element 1
row 2, column 2, element 5

SyntaxError: ignored

In [158]:
print('row', 1, 'column', 1, 'element', M[0,0])
print('row', 2, 'column', 2, 'element', M[1,1])

row 1 column 1 element 1
row 2 column 2 element 5


In [174]:
for x, row in enumerate('matrix'):
  for y, element in enumerate('rows'):
    print(f'Row {x+1}, Column {y+1}: {element}', end="")
  print()



Row 1, Column 1: rRow 1, Column 2: oRow 1, Column 3: wRow 1, Column 4: s
Row 2, Column 1: rRow 2, Column 2: oRow 2, Column 3: wRow 2, Column 4: s
Row 3, Column 1: rRow 3, Column 2: oRow 3, Column 3: wRow 3, Column 4: s
Row 4, Column 1: rRow 4, Column 2: oRow 4, Column 3: wRow 4, Column 4: s
Row 5, Column 1: rRow 5, Column 2: oRow 5, Column 3: wRow 5, Column 4: s
Row 6, Column 1: rRow 6, Column 2: oRow 6, Column 3: wRow 6, Column 4: s
