<a href="https://colab.research.google.com/github/Fernandarodg/CinD_23-II/blob/main/03_Ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structre?**

Something that let me store several values


# **2. Linear Algebra - Numpy**

Numpy=Numberical Phyton

In [2]:
# Libraries
import numpy as np

## 2.1. **Numpy arrays - Vectors and Matrices**

In [3]:
# column Vector
x = np.array([[1], [2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
# Row Vector
y = np.array([[3, 4, 5]])
print (y)
print(y.shape)

[[3 4 5]]
(1, 3)


In [5]:
# Matriz
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
# A nice trick
n, m= M.shape
print('number of rows in M:' , n)
print('number of columns in M:', m)

number of rows in M: 3
number of columns in M: 3


## 2.2. Slicing with matrices
 first row, second column
 3 number
 [3] vector
 [2,0] se quita

In [13]:
# Access 1 element

## For vector
### Column Vector
print(x[2,0])

### Row vector
print(y[0,0])

## For matrix
print(M[1,1])

3
3
5


In [10]:
# Exercise - Practice
## Using a for loop display/print the number of the row,
## the number of the column, and the element for
## every element in the Matrix M

print('Row Position:', 1, 'Column Position', 1, 'Element:',M[0,0])
print('Row Position:', 1, 'Column Position', 2, 'Element:',M[0,1])
print('Row Position:', 1, 'Column Position', 3, 'Element:',M[0,2])

for i in range(0,3):
  print('Row Position:', 1, 'Column Position', i+1, 'Element:',M[0,i])

Row Position: 1 Column Position 1 Element: 1
Row Position: 1 Column Position 2 Element: 2
Row Position: 1 Column Position 3 Element: 3


Row position: 1, Column Position:1, Element:1

Row position: 1, Column Position:2, Element:2

Row position: 1, Column Position:3, Element:3

Row position: 2, Column Position:1, Element:4

Row position: 2, Column Position:2, Element:5

Row position: 2, Column Position:3, Element:6

Row position: 3, Column Position:1, Element:7

Row position: 3, Column Position:2, Element:8

Row position: 3 ,Column Position:3, Element:9



In [12]:
for j in range(0,3):
  for i in range(0,3):
    print('Row Position:', j+1, 'Column Position', i+1, 'Element:',M[j,i])

Row Position: 1 Column Position 1 Element: 1
Row Position: 1 Column Position 2 Element: 2
Row Position: 1 Column Position 3 Element: 3
Row Position: 2 Column Position 1 Element: 4
Row Position: 2 Column Position 2 Element: 5
Row Position: 2 Column Position 3 Element: 6
Row Position: 3 Column Position 1 Element: 7
Row Position: 3 Column Position 2 Element: 8
Row Position: 3 Column Position 3 Element: 9


In [ ]:
for i in range(0,3):
  print('Row Position:', 1, 'Column Position', i+1, 'Element:',M[0,i])

In [ ]:
row 1, column 1, element 1
row 2, column 2, element 5

In [ ]:
print('row', 1, 'column', 1, 'element', M[0,0])
print('row', 2, 'column', 2, 'element', M[1,1])
print('row', 2, 'column', 2, 'element', M[1,2])

## 2.3 Extract subsets

In [20]:
# Extract an entire Row
print(M[1,])

# Extract an entire Column
print(M[:,1])

[4 5 6]
[2 5 8]


In [22]:
# Extract the elements of the
# last row and colums 2 and 3
print(M[2,1:3])

[8 9]


In [33]:
# Extract the elements of the
# first two rows and the last two columns
print(M[0:2,1:3])

[[2 3]
 [5 6]]


## 2.4 Useful methods

In [39]:
# Zeros

## One dimension
z1 = np.zeros(7)
print('z1')
print(z1)

## Two dimensions
z2 = np.zeros((3,5))
print('z2')
print(z2)

z1
[0. 0. 0. 0. 0. 0. 0.]
z2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
# Ones

## One dimension
o1 = np.ones(7)
print('o1')
print(o1)

## Two dimensions
o2 = np.ones((3,5))
print('o2')
print(o2)

o1
[1. 1. 1. 1. 1. 1. 1.]
o2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
# Full

## One dimension
f1 = np.full(3,13)
print('f1')
print(f1)

## Two dimension
f2 = np.full((3,2),17)
print('f2')
print(f2)

f1
[13 13 13]
f2
[[17 17]
 [17 17]
 [17 17]]


In [55]:
# Sequence - simple
s1 = np.arange(10)
print('s1')
print(s1)

## Not that simple
s2 = np.arange(start = 2, stop = 15)
print('s2')
print(s2)

## Custom
s3 = np.arange(start = 2, stop = 15, step =3)
print('s3')
print(s3)

s1
[0 1 2 3 4 5 6 7 8 9]
s2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
s3
[ 2  5  8 11 14]


In [59]:
# Linear Space

l1 = np.linspace(0,2,5)
print('l1')
print(l1)

l1
[0.  0.5 1.  1.5 2. ]


## 2.5. Random numbers

In [69]:
# Uniform distribution - [0, 1]
# np.random.seed(1234) - fix the similation
np.random.rand()

0.6221087710398319

In [71]:
# Example - Toss coin simulation

if np.random.rand() <= 0.5:
  print('Heads')
else:
  print('Tails')

Heads
