<a href="https://colab.research.google.com/github/Fernandarodg/CinD_23-II/blob/main/03_Ds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structre?**

Something that let me store several values


# **2. Linear Algebra - Numpy**

Numpy=Numberical Phyton

In [2]:
# Libraries
import numpy as np

## 2.1. **Numpy arrays - Vectors and Matrices**

In [3]:
# column Vector
x = np.array([[1], [2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
# Row Vector
y = np.array([[3, 4, 5]])
print (y)
print(y.shape)

[[3 4 5]]
(1, 3)


In [5]:
# Matriz
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
# A nice trick
n, m= M.shape
print('number of rows in M:' , n)
print('number of columns in M:', m)

number of rows in M: 3
number of columns in M: 3


## 2.2. Slicing with matrices
 first row, second column
 3 number
 [3] vector
 [2,0] se quita

In [7]:
# Access 1 element

## For vector
### Column Vector
print(x[2,0])

### Row vector
print(y[0,0])

## For matrix
print(M[1,1])

3
3
5


In [8]:
# Exercise - Practice
## Using a for loop display/print the number of the row,
## the number of the column, and the element for
## every element in the Matrix M

print('Row Position:', 1, 'Column Position', 1, 'Element:',M[0,0])
print('Row Position:', 1, 'Column Position', 2, 'Element:',M[0,1])
print('Row Position:', 1, 'Column Position', 3, 'Element:',M[0,2])

for i in range(0,3):
  print('Row Position:', 1, 'Column Position', i+1, 'Element:',M[0,i])

Row Position: 1 Column Position 1 Element: 1
Row Position: 1 Column Position 2 Element: 2
Row Position: 1 Column Position 3 Element: 3
Row Position: 1 Column Position 1 Element: 1
Row Position: 1 Column Position 2 Element: 2
Row Position: 1 Column Position 3 Element: 3


Row position: 1, Column Position:1, Element:1

Row position: 1, Column Position:2, Element:2

Row position: 1, Column Position:3, Element:3

Row position: 2, Column Position:1, Element:4

Row position: 2, Column Position:2, Element:5

Row position: 2, Column Position:3, Element:6

Row position: 3, Column Position:1, Element:7

Row position: 3, Column Position:2, Element:8

Row position: 3 ,Column Position:3, Element:9



In [9]:
for j in range(0,3):
  for i in range(0,3):
    print('Row Position:', j+1, 'Column Position', i+1, 'Element:',M[j,i])

Row Position: 1 Column Position 1 Element: 1
Row Position: 1 Column Position 2 Element: 2
Row Position: 1 Column Position 3 Element: 3
Row Position: 2 Column Position 1 Element: 4
Row Position: 2 Column Position 2 Element: 5
Row Position: 2 Column Position 3 Element: 6
Row Position: 3 Column Position 1 Element: 7
Row Position: 3 Column Position 2 Element: 8
Row Position: 3 Column Position 3 Element: 9


In [10]:
for i in range(0,3):
  print('Row Position:', 1, 'Column Position', i+1, 'Element:',M[0,i])

Row Position: 1 Column Position 1 Element: 1
Row Position: 1 Column Position 2 Element: 2
Row Position: 1 Column Position 3 Element: 3


In [11]:
row 1, column 1, element 1
row 2, column 2, element 5

SyntaxError: ignored

In [13]:
print('row', 1, 'column', 1, 'element', M[0,0])
print('row', 2, 'column', 2, 'element', M[1,1])
print('row', 2, 'column', 2, 'element', M[1,2])

row 1 column 1 element 1
row 2 column 2 element 5
row 2 column 2 element 6


## 2.3 Extract subsets

In [14]:
# Extract an entire Row
print(M[1,])

# Extract an entire Column
print(M[:,1])

[4 5 6]
[2 5 8]


In [15]:
# Extract the elements of the
# last row and colums 2 and 3
print(M[2,1:3])

[8 9]


In [16]:
# Extract the elements of the
# first two rows and the last two columns
print(M[0:2,1:3])

[[2 3]
 [5 6]]


## 2.4 Useful methods

In [17]:
# Zeros

## One dimension
z1 = np.zeros(7)
print('z1')
print(z1)

## Two dimensions
z2 = np.zeros((3,5))
print('z2')
print(z2)

z1
[0. 0. 0. 0. 0. 0. 0.]
z2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# Ones

## One dimension
o1 = np.ones(7)
print('o1')
print(o1)

## Two dimensions
o2 = np.ones((3,5))
print('o2')
print(o2)

o1
[1. 1. 1. 1. 1. 1. 1.]
o2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# Full

## One dimension
f1 = np.full(3,13)
print('f1')
print(f1)

## Two dimension
f2 = np.full((3,2),17)
print('f2')
print(f2)

f1
[13 13 13]
f2
[[17 17]
 [17 17]
 [17 17]]


In [20]:
# Sequence - simple
s1 = np.arange(10)
print('s1')
print(s1)

## Not that simple
s2 = np.arange(start = 2, stop = 15)
print('s2')
print(s2)

## Custom
s3 = np.arange(start = 2, stop = 15, step =3)
print('s3')
print(s3)

s1
[0 1 2 3 4 5 6 7 8 9]
s2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
s3
[ 2  5  8 11 14]


In [21]:
# Linear Space

l1 = np.linspace(0,2,5)
print('l1')
print(l1)

l1
[0.  0.5 1.  1.5 2. ]


## 2.5. Random numbers

In [12]:
# Uniform distribution - [0, 1]
# np.random.seed(1234) - fix the similation
np.random.rand()

0.35306595490410686

In [22]:
# Example - Toss coin simulation

if np.random.rand() <= 0.5:
  print('Heads')
else:
  print('Tails')

Tails


In [29]:
# Example - Coin Toss simulation

if np.random.rand() <= 0.5:
  print('Heads')
else:
  print('Tails')

Tails


if / else with more than 2 options

In [37]:
# Example - three options

toss = np.random.rand()

if toss <= 0.4:
  print('green')
elif toss > 0.4 and toss <= 0.6:
  print('blue')
else:
  print('red')


green


In [54]:
# Exercise
## Simulate three coin tosses and present the results
## according these rules:

## 1. Three Heads, Result: 'You win COP 100K'
## 2. Three Tails, Result: 'You win COP 90K'
## 3. Otherwise, Result: 'You lose'

In [77]:
toss1 = np.random.rand()
toss2 = np.random.rand()
toss3 = np.random.rand()

if toss1 <= 0.5 and toss2 <= 0.5 and toss3 <= 0.5:
  print('Three Heads:', 'You win COP 100K')
elif toss1 > 0.5 and toss2 > 0.5 and toss3 > 0.5:
  print('Three Tails:', 'You win COP 90K')
else:
  print('You loose')

You loose


In [78]:
np.random.rand(3)

array([0.69178113, 0.36105507, 0.94470269])

In [90]:
tosses = np.random.rand(3)

if np.all(tosses <= 0.5):
  print('Three Heads:', 'You win COP 100K')
elif np.all(tosses > 0.5):
  print('Three Tails:', 'You win COP 90K')
else:
  print('You loose')

Three Tails: You win COP 90K


In [94]:
# Example - triangular distribution cuantas unidades se puede vender, 7 unidades
np.random.triangular(100, 200, 500, 7)

array([208.31934761, 315.47824837, 292.16252462, 479.03458267,
       173.23594224, 107.94650017, 284.39598848])

In [102]:

## Sales
bs = 100
av = 200
gs = 500

## Probabilities
bs = 1/30
pg = 8/30


n= 7 # number of days ot iterate

for i in range(1, n+1):
  day = np.random.rand()
  if day <= pb:
    print(bs)
  elif day > 1 - pg:
    print(gs)
  else:
    print(av)

NameError: ignored